media: public/works/media
content:
  - name: posts
    label: Posts
    type: collection
    path: '_works'
    view:
      fields:
        [ title, published, date, image ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: image
        label: Image
        type: image
      - name: body
        label: Body
        type: rich-text